### ISSUE TITLE
problem dependences

### ISSUE THREAD

**Issue by cheurfa20081984** [Chargily/chargily-epay-csharp#7]
ConsoleTest problem 
et dependances  probleme

**Comment by rainxh11** [comment]
This package is using the official  `Microsoft.Extensions.DependencyInjection` package to register itself as a singleton client.
the most straightforward way to use it would be:
```csharp
using chargily.epay.csharp;

var builder = WebApplication.CreateBuilder(args); <--- Web or any generic Host Builder

builder.Services.AddChargilyEpayGateway("[API_KEY]");
```
